### ISSUE TITLE
Ensure postman.json collection meets requirements

### ISSUE THREAD

**Issue by Ram-Raghav-S** [Scriptorium-CSC309/web#45]
The postman collection must be an export of all the APIs that are importable into Postman. The TA will use Postman to test the API, so it is important that the collection is comprehensive, well-organized, and self-explanatory. All the POST data, headers, and GET query parameters must be pre-filled and editable in that collection.

Your postman collection should automatically set and use the tokens without having the TAs to manually paste them every time. More information can be found [here](https://community.postman.com/t/set-response-value-as-variable-in-test/46213/2).

Ensure that all routes are covered, if not add the coverage.

**Comment by jerryy2021** [comment]
For this one perhaps we could each add docs for our own API requests?
